project:
  type: website

website:
  title: dublin-core-metadata-enhancer
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://dokumentation.stadtgeschichtebasel.ch/dublin-core-metadata-enhancer/
  repo-url: https://github.com/Stadt-Geschichte-Basel/dublin-core-metadata-enhancer/
  issue-url: https://github.com/Stadt-Geschichte-Basel/dublin-core-metadata-enhancer/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    title: Dublin Core Metadata Enhancer
    tools-collapse: true
    tools:
      - icon: github
        url: https://github.com/Stadt-Geschichte-Basel/dublin-core-metadata-enhancer/
        aria-label: GitHub Repository
    left:
      - text: Home
        href: index.qmd
      - text: Documentation
        menu:
          - text: Metadata Enhancement
            href: documentation/metadata-enhancement.md

  sidebar:
    contents:
      - section: dublin-core-metadata-enhancer
        href: index.qmd
        contents:
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Data)
            href: LICENSE-CCBY.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md
      - section: Documentation
        contents:
          - text: Metadata Enhancement Pipeline
            href: documentation/metadata-enhancement.md

format:
  html:
    toc: true
    theme: cosmo
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    css: styles.css
    mainfont: Euclid Circular B
    mermaid:
      theme: neutral

freeze: true

editor: visual
